# Generated by Django 3.2.24 on 2024-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('branch', models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore')], max_length=50)),
                ('value_for_money', models.CharField(choices=[('excellent', 'Excellent'), ('satisfied', 'Satisfied'), ('to_be_improved', 'To be Improved')], max_length=20)),
                ('packaging', models.CharField(choices=[('excellent', 'Excellent'), ('satisfied', 'Satisfied'), ('to_be_improved', 'To be Improved')], max_length=20)),
                ('quality', models.CharField(choices=[('excellent', 'Excellent'), ('satisfied', 'Satisfied'), ('to_be_improved', 'To be Improved')], max_length=20)),
                ('display', models.CharField(choices=[('excellent', 'Excellent'), ('satisfied', 'Satisfied'), ('to_be_improved', 'To be Improved')], max_length=20)),
                ('variety', models.CharField(choices=[('excellent', 'Excellent'), ('satisfied', 'Satisfied'), ('to_be_improved', 'To be Improved')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('employee_name_and_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('voice_recording', models.FileField(blank=True, null=True, upload_to='recordings/')),
            ],
        ),
    ]
