# Generated by Django 3.2.24 on 2024-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='branch',
            field=models.CharField(choices=[('Adayar', 'Adayar'), ('Alwarpet', 'Alwarpet'), ('Ambattur', 'Ambattur'), ('Anna Nagar', 'Anna Nagar'), ('Ashok Nagar', 'Ashok Nagar'), ('Avadi', 'Avadi'), ('Ayanavaram', 'Ayanavaram'), ('Bazullah Road', 'Bazullah Road'), ('Besant Nagar', 'Besant Nagar'), ('Chrompet', 'Chrompet'), ('Egmore', 'Egmore'), ('Kanchipuram', 'Kanchipuram'), ('Kanchi Gandhi Road', 'Kanchi Gandhi Road'), ('Karapakkam', 'Karapakkam'), ('Kathipara', 'Kathipara'), ('Kelambakkam', 'Kelambakkam'), ('Korattur', 'Korattur'), ('Luz New', 'Luz New'), ('Madipakkam', 'Madipakkam'), ('Medavakkam', 'Medavakkam'), ('Mogappair', 'Mogappair'), ('Mylapore', 'Mylapore'), ('Nanganallur', 'Nanganallur'), ('Nanganallur West', 'Nanganallur West'), ('Nungambakkam', 'Nungambakkam'), ('Perambur', 'Perambur'), ('Porur', 'Porur'), ('Pondicherry', 'Pondicherry'), ('Purasai Palace', 'Purasai Palace'), ('Saidapet', 'Saidapet'), ('Tambaram West', 'Tambaram West'), ('Thiruvallur', 'Thiruvallur'), ('Thiruvanmiyur', 'Thiruvanmiyur'), ('Thiruvannamalai', 'Thiruvannamalai'), ('Thuraipakkam', 'Thuraipakkam'), ('Triplicane', 'Triplicane'), ('Usman Road', 'Usman Road'), ('Vadapalani', 'Vadapalani'), ('Valasaravakkam', 'Valasaravakkam'), ('Velachery', 'Velachery'), ('Villivakkam', 'Villivakkam'), ('VN Road T.Nagar', 'VN Road T.Nagar'), ('Venus Colony', 'Venus Colony'), ('West Mambalam', 'West Mambalam'), ('Chennai Airport', 'Chennai Airport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
